<a href="https://colab.research.google.com/github/onleey/Machine-Learning_demo/blob/master/p601_%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%84%EC%B2%98%EB%A6%AC_%EB%B2%94%EC%A3%BC%ED%98%95%EB%B3%80%EC%88%98%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 변수
기계학습에서는  column = feature = dimension = variable을 혼용해서 사용한다.  


1 범주형 변수(Categorical Data)=질적변수(Qualitative Variable) : 몇개의 범주로 나누어진 자료를 의미
 - 명목형(Nominal Data): 성별, 성공여부, 혈액형 등 순서를 매길 수 없고 셀수 있다는 특징이 있다.
 - 순서형(Ordinal Data) : 교육수준, 만족도등  그들 사이에 순서 관계가 존재하는 자료


2 수치형 변수 = 양적변수(Quantitative Variable): 이산형과 연속형으로 이루어진 자료를 의미
  - 이산형(Discrete Data) :출산횟수, 불량품 수, 사고건수, 차량대수 등 이산적인 값을 갖는 데이터로  수치적인 의미를 가지나 소수점의 형태로 표현되지 못하는 데이터를 의미
  - 연속형(Continuous Data) : 신장, 체중, 시간, 길이 등 연속적인 값을 가지고 소수점으로 표현이 가능한 데이터를 의미




|        |  질적변수(Category)      | 양적변수(Numeric)          |
|--- |--- |---|
|질적변수|Cross Table               | Box Plot                   |
|        |Mosaic Plot               | 범주(Category)별 통계분석  |
|양적변수|Box Plot                  | Correlation                |
|        |범주(Category)별 통계분석 | Regression                 |
|        |                          | Scatter Plot               |


더미변수란 범주형 변수에 있는 범주 각각을 컬럼으로 변경하고, 원본 컬럼의 값이 해당 범주에 속하는지 여부에 따라 1 혹은 0으로 채운 변수이다.  
pd.get_dummies(df, columns=['범주형변수'])



더미변수란 범주형 변수에 있는 범주 각각을 컬럼으로 변경하고, 원본 컬럼의 값이 해당 범주에 속하는지 여부에 따라 1 혹은 0으로 채운 변수이다.  




pd.get_dummies(df, columns=['범주형변수'])
- 범주형 변수 변환
  - 원핫인코딩(One-hot-encoding), 더미코딩(dummy coding), 이펙트코딩(Effect coding), 숫자로 표현된 범주형 특성, 레이블인코딩(Label encoding), 특징 해싱(Feature Hashing)


- 수치형 변수 변환 (*옆의 괄호는 Scikit Learn의 함수명)
  - 선형변환: 최소최대 스케일링(MinMaxScaler), 표준화(StandardScaler), 로버스트 스케일링(RobustScaler), 균등분포/RankGauss (QuantileTransformer)
  - 비선형변환: 로그변환, 거듭제곱변환(PowerTransformer - Boxcox, YeoJohnson), 정규화(Normalizer - L1, L2, Max)
  - 기타: 구간분할 (=이산화, binning), 순위 변환

*** iris데이터의 target값인 범주형 변수를 더비변수 형태로 대체 ***

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
#print(iris)
print(dir(iris))
print(type(iris))
print(iris.DESCR)

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']
<class 'sklearn.utils._bunch.Bunch'>
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76  

In [ ]:
iris = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris['target'] =load_iris().target
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
iris.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
70                 5.9               3.2                4.8               1.8   
20                 5.4               3.4                1.7               0.2   
111                6.4               2.7                5.3               1.9   
16                 5.4               3.9                1.3               0.4   
60                 5.0               2.0                3.5               1.0   

     target  
70        1  
20        0  
111       2  
16        0  
60        1

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [ ]:
iris.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [ ]:
iris['target'] = iris['target'].replace([0,1,2],['setosa','versicolour','verginica'])
#iris['target'] = iris['target'].map({0:'Setosa', 1:'Versicolour', 2:'Virginica'})
iris['target']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    verginica
146    verginica
147    verginica
148    verginica
149    verginica
Name: target, Length: 150, dtype: object

In [ ]:
#iris 데이터셋의 target 변수의 값을 더미로 처리해줌
iris_dummy = pd.get_dummies(iris,columns=['target'])
iris_dummy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target_setosa  target_verginica  target_versicolour  
0              1                 0                   0  
1              1                 0                   0  
2              1                 0                   0  
3              1                 0                   0  
4              1                 0                   0

In [ ]:
iris_dummy.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
65                 6.7               3.1                4.4               1.4   
122                7.7               2.8                6.7               2.0   
144                6.7               3.3                5.7               2.5   
43                 5.0               3.5                1.6               0.6   
40                 5.0               3.5                1.3               0.3   

     target_setosa  target_verginica  target_versicolour  
65               0                 0                   1  
122              0                 1                   0  
144              0                 1                   0  
43               1                 0                   0  
40               1                 0                   0

### label encoding
label encoding은 문자열 데이터에 고유한 라벨번호를 매기는것이다.

In [ ]:
# from sklearn.datasets import load_iris
# iris_load_iris()

import seaborn as sns
iris = sns.load_dataset('iris')
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
62           6.0          2.2           4.0          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
34           4.9          3.1           1.5          0.2      setosa
83           6.0          2.7           5.1          1.6  versicolor
50           7.0          3.2           4.7          1.4  versicolor

In [ ]:
iris.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
#map으로 label encoding 할수있다
iris.species.map({'setosa':0,'versicolor':1,'virginica':2})

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [ ]:
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
80            5.5          2.4           3.8          1.1  versicolor
123           6.3          2.7           4.9          1.8   virginica
101           5.8          2.7           5.1          1.9   virginica
24            4.8          3.4           1.9          0.2      setosa
143           6.8          3.2           5.9          2.3   virginica

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
ll = LabelEncoder()

In [ ]:
ll.fit_transform(iris.species)
ll.fit_transform(iris['species']) #리스트형태

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width    species
26            5.0          3.4           1.6          0.4     setosa
116           6.5          3.0           5.5          1.8  virginica
123           6.3          2.7           4.9          1.8  virginica
34            4.9          3.1           1.5          0.2     setosa
22            4.6          3.6           1.0          0.2     setosa

In [ ]:
#2차원으로 넣으면 warning이 뜬다
ll.fit_transform(iris['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.utils import column_or_1d

column_or_1d(iris['species'])
ll.fit_transform(column_or_1d(iris['species']))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
26           5.0          3.4           1.6          0.4      setosa
6            4.6          3.4           1.4          0.3      setosa
61           5.9          3.0           4.2          1.5  versicolor
20           5.4          3.4           1.7          0.2      setosa
37           4.9          3.6           1.4          0.1      setosa

### onehotencoding

문자열 데이터를 column으로 바꾸고, 해당하는 위치에만 1로 한다.

In [53]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()

In [54]:
ohe.fit_transform(iris[['species']])

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [55]:
ohe.fit_transform(iris[['species']]).toarray()
#toarray()는 numpy로 바꿔줘서 값을 확인 할 수 있다.

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [56]:
#다시 문자로 바꿀 수 있다.
ohe.inverse_transform([[1,0,0],[0,1,0],[0,0,1]])

array([['setosa'],
       ['versicolor'],
       ['virginica']], dtype=object)